#release configuration
#Fri Jun 12 12:55:20 UTC 2026
projectVersionPolicyId=default
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
remoteTagging=true
scm.commentPrefix=[maven-release-plugin] 
releaseStrategyId=default
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
pinExternals=false
completedPhase=check-poms
scm.url=scm\:git\:https\://github.com/SchoolBielan1KI/SchoolApp.git
scm.developmentCommitComment=@{prefix} prepare for next development iteration
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
project.scm.com.school\:school-schedule.tag=HEAD
project.scm.com.school\:school-schedule.developerConnection=scm\:git\:https\://github.com/SchoolBielan1KI/SchoolApp.git
scm.tagNameFormat=v@{project.version}
pushChanges=true
project.scm.com.school\:school-schedule.connection=scm\:git\:https\://github.com/SchoolBielan1KI/SchoolApp.git
project.scm.com.school\:school-schedule.url=https\://github.com/SchoolBielan1KI/SchoolApp
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
exec.pomFileName=pom.xml
