name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "mongodb" ]

jobs:
  static-analysis:
    name: CI / Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run Checkstyle
        run: mvn validate --no-transfer-progress

  build-and-unit-tests:
    name: CI / Build and Unit Tests
    runs-on: ubuntu-latest
    needs: static-analysis
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build and run unit tests
        run: mvn clean package --no-transfer-progress
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/

  integration-tests:
    name: CI / Integration Tests
    runs-on: ubuntu-latest
    needs: static-analysis
    env:
      MONGO_URI: mongodb+srv://belannvv_db_user:XsaqpqLuY7PoLOMh@cluster0.cbkl4qr.mongodb.net/school_db?appName=Cluster0
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run Integration Tests
        run: mvn verify -Dsurefire.skip=true --no-transfer-progress

  docker-publish:
    name: Publish Docker
    needs: [build-and-unit-tests, integration-tests]
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-publish.yml

  deploy-render-pr:
    name: Deploy to Render (PR)
    needs: docker-publish
    permissions:
      contents: read
    uses: ./.github/workflows/render-deploy.yml
    secrets: inherit

  e2e-tests:
    name: E2E UI Tests
    needs: deploy-render-pr
    runs-on: ubuntu-latest
    env:
      E2E_BASE_URL: https://schoolapp-57rw.onrender.com
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run E2E Tests
        # Тут ми передаємо URL твого Render-сервісу
        run: mvn test -P e2e-ui -DE2E_BASE_URL=https://schoolapp-5.onrender.com